#!/usr/bin/php
<?php
define('TOKEN', '');
define('CHATID', '');


if (TOKEN)
	$token = TOKEN;
else
	$token = getenv('TELENOTY_TOKEN');

if (CHATID)
	$chatid = CHATID;
else
	$chatid = getenv('TELENOTY_CHATID');

if (!$token || !$chatid)
	return;

if (posix_isatty(STDIN))
    return;

if (!strlen($mail = @file_get_contents('php://stdin')))
    return;


$mail = str_replace("\r", "", $mail);
list($head, $body) = explode("\n\n", $mail, 2);

$head = "\n" . $head . "\n";

preg_match('/\nFrom: (.+?)\n/m', $head, $matches);
$from = $matches[1];
preg_match('/\nTo: (.+?)\n/m', $head, $matches);
$to = $matches[1];

if (!$from && !$to)
    return;


$data = "From: " . $from . "\nTo: " . $to . "\n\n" . $body;

$json = json_encode(array(
    'chat_id' => $chatid,
    'disable_web_page_preview' => true,
    'text' => $data
));

$context = array(
    "http" => array(
        "method"  => "POST",
        "header"  => "Content-Type: application/json\r\n",
        "content" => $json
    )
);

file_get_contents('https://api.telegram.org/bot' . $token . '/sendMessage', '', stream_context_create($context));

