#!/usr/bin/php
<?php
// telenoty
// Copyright (c) 2020 silverintegral
// Released under the MIT license

define('TOKEN', '');
define('CHATID', '');


if (TOKEN)
	$token = TOKEN;
else
	$token = getenv('TELENOTY_TOKEN');

if (CHATID)
	$chatid = CHATID;
else
	$chatid = getenv('TELENOTY_CHATID');

if (!$token || !$chatid)
	return;


$msg = '';

if (!posix_isatty(STDIN))
	$msg = @file_get_contents('php://stdin');

if (!strlen($msg))
	$msg = $argv[1];

if (!strlen($msg))
	return;


$json = json_encode(array(
    'chat_id' => $chatid,
    'disable_web_page_preview' => true,
    'text' => $msg
));

$con = array(
    "http" => array(
        "method"  => "POST",
        "header"  => "Content-Type: application/json\r\n",
        "content" => $json
    )
);

file_get_contents('https://api.telegram.org/bot' . $token . '/sendMessage', '', stream_context_create($con));

